### PR TITLE
M3u8 fix addtional headers

### PR DESCRIPTION
**Pull request by nicechester**
OnDemandKorea plugin fix for the website changes.
- Added headers to avoid urllib error
- Grep .m3u8 instead of mp4

### CODE REVIEW

**Comment by ianhmcleod** [comment]
thanks for the merge request, i'll take a look at it

**Comment by ianhmcleod** [comment]
looks good -- merged

**Comment by nicechester** [comment]
thanks!

**Comment by wyim-pgl** [comment]
Hello,

Do you guys have any plan to add login function?

Thank you.

**Pull request merged**
